### ISSUE TITLE
Issues running the extension

### ISSUE THREAD

**Issue by deadmantfa** [unyii2/yii2-panel#2]
yii\base\UnknownPropertyException: Getting unknown property: backend\modules\panel\Module::panels in /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/bbv2/webservice/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('panels')
#1 /var/www/bbv2/webservice/vendor/unyii2/yii2-panel/src/PanelWidget.php(22): yii\di\ServiceLocator->__get('panels')
#2 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/BaseObject.php(109): unyii2\yii2panel\PanelWidget->init()
#3 [internal function]: yii\base\BaseObject->__construct(Array)
#4 /var/www/bbv2/webservice/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#5 /var/www/bbv2/webservice/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('unyii2\\yii2pane...', Array, Array)
#6 /var/www/bbv2/webservice/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('unyii2\\yii2pane...', Array, Array)
#7 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Widget.php(137): yii\BaseYii::createObject(Array)
#8 /var/www/bbv2/webservice/backend/modules/panel/views/default/index.php(3): yii\base\Widget::widget(Array)
#9 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/bbv2/w...')
#10 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/bbv2/w...', Array)
#11 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/bbv2/w...', Array, Object(backend\modules\panel\controllers\DefaultController))
#12 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(backend\modules\panel\controllers\DefaultController))
#13 /var/www/bbv2/webservice/backend/modules/panel/controllers/DefaultController.php(18): yii\base\Controller->render('index')
#14 [internal function]: backend\modules\panel\controllers\DefaultController->actionIndex()
#15 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#18 /var/www/bbv2/webservice/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('panel', Array)
#19 /var/www/bbv2/webservice/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /var/www/bbv2/webservice/backend/web/index.php(19): yii\base\Application->run()
#21 {main}

**Comment by deadmantfa** [comment]
fixed. Sorry false report
